language: python
python:
  - '3.8'

branches:
  only:
    - master

addons:
  firefox: latest

before_install:
   - sudo apt-get update
   

install:
   - pip3 install --upgrade setuptools
   - pip3 install -r requirements.txt
   - pip3 install python-secrets
   - pip3 install django-secrets

services:
   - postgresql

env: 
   - DJANGO_SETTINGS_MODULE=set.set.travis_settings
   - global: MOZ_HEADLESS=1


script: 
   - cd set
   - ./manage.py test tests