# Generated by Django 3.1.6 on 2021-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0004_auto_20210210_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='image_couverture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
