# Generated by Django 3.1.6 on 2021-02-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0006_auto_20210210_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sets',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='sets',
            name='utilisateur',
        ),
    ]
