# Generated by Django 3.1.6 on 2021-02-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210209_2229'),
        ('sets', '0008_jaimepublicationevenement_jaimepublicationset'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaimepublicationevenement',
            name='jaimeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.utilisateurs'),
        ),
        migrations.AddField(
            model_name='jaimepublicationset',
            name='jaimeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.utilisateurs'),
        ),
    ]
