# Generated by Django 3.1.7 on 2021-03-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0010_auto_20210219_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationset',
            name='media1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicationset',
            name='media2',
            field=models.ImageField(upload_to=''),
        ),
    ]
