# Generated by Django 3.1.7 on 2021-03-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0011_auto_20210303_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationset',
            name='admin_controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationset',
            name='admin_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicationset',
            name='media1',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicationset',
            name='media2',
            field=models.FileField(upload_to=''),
        ),
    ]
