# Generated by Django 3.1.7 on 2021-03-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0012_auto_20210303_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationset',
            old_name='admin_controlled',
            new_name='control_admin',
        ),
        migrations.RenameField(
            model_name='publicationset',
            old_name='admin_hide',
            new_name='masquage_admin',
        ),
    ]
