# Generated by Django 3.1.7 on 2021-03-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0013_auto_20210303_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenements',
            name='statut_fermeture_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationevenement',
            name='control_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationevenement',
            name='masquage_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sets',
            name='statut_fermeture_admin',
            field=models.BooleanField(default=False),
        ),
    ]
