# Generated by Django 5.0.3 on 2024-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0014_auto_20210303_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='image_couverture',
            field=models.FileField(upload_to=''),
        ),
    ]
