# Generated by Django 3.1.6 on 2021-02-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.ManyToManyField(related_name='contact_owner', through='user.Contact', to='user.Utilisateurs')),
                ('message', models.ManyToManyField(related_name='_utilisateurs_message_+', through='user.Message', to='user.Utilisateurs')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='which_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e', to='user.utilisateurs'),
        ),
        migrations.AddField(
            model_name='message',
            name='which_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f', to='user.utilisateurs'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='user.utilisateurs'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='user.utilisateurs'),
        ),
    ]
