# Generated by Django 3.1.6 on 2021-02-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='name',
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='adresse_mail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='code_de_reinitialisation_de_mot_de_passe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='image_profil',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='mot_de_passe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
