# Generated by Django 3.1.6 on 2021-02-19 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210209_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='message',
        ),
    ]
