# Generated by Django 3.1.7 on 2021-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210219_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='code_de_reinitialisation_de_mot_de_passe',
            new_name='cle_dactivation_de_compte',
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='cle_de_reinitialisation_de_mot_de_passe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='statut_activation_compte',
            field=models.BooleanField(default=False),
        ),
    ]
