# Generated by Django 5.0.3 on 2024-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_utilisateurs_statut_blocage_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='statut_activation_compte',
            field=models.BooleanField(default=True),
        ),
    ]
